apiVersion: v2
name: clinic-app
description: Aplicatie de management al programarilor pentru o clinica medicala
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "15.5.38"
    repository: "https://charts.bitnami.com/bitnami"
    alias: postgresql