name: clinic-app
namespace: clinic

backend:
  image:
    repository: ghcr.io/ionutsandu1996/medical-clinic-app/clinic-backend
    tag: "v1.0.4"
    pullPolicy: Always
  replicaCount: 1

frontend:
  image:
    repository: ghcr.io/ionutsandu1996/medical-clinic-app/clinic-frontend
    tag: "v1.0.1"
    pullPolicy: Always
  replicaCount: 1

ports:
  backend: 3001
  frontend: 80

ingress:
  enabled: true
  host: clinic.local

config:
  data:
    NODE_ENV: "production"
    PORT: "3001"
    DB_HOST: "clinic-app-postgresql"
    DB_PORT: "5432"
    DB_NAME: "clinic_db"
    DB_USER: "clinic_user"
    DB_POOL_MIN: "2"
    DB_POOL_MAX: "10"
    CORS_ORIGIN: "http://clinic.local"
    JWT_SECRET_KEY: "jwt_secret"

secret:
  DB_PASSWORD: "changeit"
  POSTGRES_PASSWORD: "changeit"
  JWT_SECRET: "7bf0988538ef6be4ef4160fa4cad0119fc102a04e46bf90583ab7686f774ed50"

postgresql:
  enabled: true
  image:
    tag: latest
  auth:
    database: "clinic_db"
    username: "clinic_user"
    password: "changeit"
    postgresPassword: "changeit"
  primary:
    persistence:
      enabled: true
      size: 1Gi