apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: clinic-backend
  template:
    metadata:
      labels:
        app: clinic-backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/deployment: {{ include (print $.Template.BasePath "/deployment-backend.yaml") . | sha256sum }}
    spec:
      containers:
        - name: clinic-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.backend }}
          envFrom:
            - configMapRef:
                name: clinic-config
            - secretRef:
                name: {{ .Values.name }}-secret
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.backend }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.backend }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"