apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: clinic-frontend
  template:
    metadata:
      labels:
        app: clinic-frontend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/deployment: {{ include (print $.Template.BasePath "/deployment-frontend.yaml") . | sha256sum }}
    spec:
      containers:
        - name: clinic-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.frontend }}
          envFrom:
            - configMapRef:
                name: clinic-config
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.ports.frontend }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.ports.frontend }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"