apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: clinic
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | b64enc | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | b64enc | quote }}